name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t laba45:lab45 -f laba4-5/Dockerfile .

      - name: Log in to Docker Hub
        run: docker login -u l1ttleje -p jne3tzNpjB
        
      - name: IDK
        run: docker tag lab45 l1ttleje/lab45
        
      - name: Push
        run: docker push laba45:lab45
