name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t l1ttleje/laba45:lab45 -f laba4-5/Dockerfile .

      - name: Log in to Docker Hub
        run: docker login -u l1ttleje -p dckr_pat_9Lb9lAf8U0zfckCoxRdtH7wmlIs
        
      - name: Push
        run: docker push l1ttleje/laba45:lab45
